# Assignment 14 : Feature Engineering, Encoding, Scaling & Pipelines

In [112]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## PART A - Feature Engineering

### Task 1: Creating New Features

In [113]:
# Read the dataset
data=pd.read_json('product_data.json')

In [114]:
# Convert into DataFrame

data=pd.DataFrame(data)

In [115]:
data.head()

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,stock_quantity,customer_rating,is_returned,return_reason
0,FB000001,Outerwear,Zara,Spring,XL,Red,196.01,0.0,196.01,2025-07-05T00:00:00.000,37,3.0,False,None
1,FB000002,Tops,Uniqlo,Winter,L,Pink,119.64,0.0,119.64,2025-08-06T00:00:00.000,2,2.5,False,None
2,FB000003,Accessories,Uniqlo,Winter,None,Black,33.80,0.0,33.80,2025-08-06T00:00:00.000,22,4.3,False,None
3,FB000004,Shoes,Uniqlo,Spring,XL,Black,75.36,0.0,75.36,2025-07-07T00:00:00.000,48,2.6,False,None
4,FB000005,Tops,Banana Republic,Winter,XL,Black,105.02,0.0,105.02,2025-08-06T00:00:00.000,10,NaN,False,None

In [116]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2176 entries, 0 to 2175
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           2176 non-null   object
 1   category             2176 non-null   object
 2   brand                2176 non-null   object
 3   season               2176 non-null   object
 4   size                 1685 non-null   object
 5   color                2176 non-null   object
 6   original_price       2176 non-null   float64
 7   markdown_percentage  2176 non-null   float64
 8   current_price        2176 non-null   float64
 9   purchase_date        2176 non-null   object
 10  stock_quantity       2176 non-null   int64
 11  customer_rating      1814 non-null   float64
 12  is_returned          2176 non-null   bool
 13  return_reason        320 non-null    object
dtypes: bool(1), float64(4), int64(1), object(8)
memory usage: 223.3+ KB

In [117]:
# 1. Identity atleast 2 existing columns from your dataset

data[['category','brand','stock_quantity']]

         category            brand  stock_quantity
0       Outerwear             Zara              37
1            Tops           Uniqlo               2
2     Accessories           Uniqlo              22
3           Shoes           Uniqlo              48
4            Tops  Banana Republic              10
...           ...              ...             ...
2171         Tops            Mango              10
2172      Dresses  Banana Republic               1
2173  Accessories  Banana Republic              40
2174      Bottoms       Ann Taylor              20
2175        Shoes       Ann Taylor              23

[2176 rows x 3 columns]

In [118]:
# 2. Create new meaningful features

In [119]:
# Create a column to price per unit

data['Price per Unit']=data['original_price']

In [120]:
data.head()

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,stock_quantity,customer_rating,is_returned,return_reason,Price per Unit
0,FB000001,Outerwear,Zara,Spring,XL,Red,196.01,0.0,196.01,2025-07-05T00:00:00.000,37,3.0,False,None,196.01
1,FB000002,Tops,Uniqlo,Winter,L,Pink,119.64,0.0,119.64,2025-08-06T00:00:00.000,2,2.5,False,None,119.64
2,FB000003,Accessories,Uniqlo,Winter,None,Black,33.80,0.0,33.80,2025-08-06T00:00:00.000,22,4.3,False,None,33.80
3,FB000004,Shoes,Uniqlo,Spring,XL,Black,75.36,0.0,75.36,2025-07-07T00:00:00.000,48,2.6,False,None,75.36
4,FB000005,Tops,Banana Republic,Winter,XL,Black,105.02,0.0,105.02,2025-08-06T00:00:00.000,10,NaN,False,None,105.02

In [121]:
# Create a new column of total value

data['Total Value']=(data['original_price'] * data['stock_quantity'])

In [122]:
data.head()

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,stock_quantity,customer_rating,is_returned,return_reason,Price per Unit,Total Value
0,FB000001,Outerwear,Zara,Spring,XL,Red,196.01,0.0,196.01,2025-07-05T00:00:00.000,37,3.0,False,None,196.01,7252.37
1,FB000002,Tops,Uniqlo,Winter,L,Pink,119.64,0.0,119.64,2025-08-06T00:00:00.000,2,2.5,False,None,119.64,239.28
2,FB000003,Accessories,Uniqlo,Winter,None,Black,33.80,0.0,33.80,2025-08-06T00:00:00.000,22,4.3,False,None,33.80,743.60
3,FB000004,Shoes,Uniqlo,Spring,XL,Black,75.36,0.0,75.36,2025-07-07T00:00:00.000,48,2.6,False,None,75.36,3617.28
4,FB000005,Tops,Banana Republic,Winter,XL,Black,105.02,0.0,105.02,2025-08-06T00:00:00.000,10,NaN,False,None,105.02,1050.20

In [123]:
# Make a def to define the revenue category

def Revenue(num):
    if num>0 and num<1000:
        return 'Low'
    elif num>=1000 and num<5000:
        return 'Medium'
    elif num>=5000 and num<10000:
        return 'High'
    else:
        return 'Very High'

In [124]:
# Create a new column of Revenue Category

data['Revenue Category']=data['Total Value'].apply(Revenue)

### Task 2: Handling Data & Text Features

In [125]:
# Convert purchase_data column into datetime format

data['purchase_date']=pd.to_datetime(data['purchase_date'],errors='coerce')

In [126]:
data['purchase_date']

0      2025-07-05
1      2025-08-06
2      2025-08-06
3      2025-07-07
4      2025-08-06
          ...
2171   2025-08-06
2172   2025-08-06
2173   2025-08-06
2174   2025-08-06
2175   2025-08-06
Name: purchase_date, Length: 2176, dtype: datetime64[ns]

In [127]:
# Create the month , year , day column

data['Purchase Year']=data['purchase_date'].dt.year
data['Purchase Month']=data['purchase_date'].dt.month_name()
data['Purchase Day']=data['purchase_date'].dt.day

In [128]:
data.head()

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,stock_quantity,customer_rating,is_returned,return_reason,Price per Unit,Total Value,Revenue Category,Purchase Year,Purchase Month,Purchase Day
0,FB000001,Outerwear,Zara,Spring,XL,Red,196.01,0.0,196.01,2025-07-05,37,3.0,False,None,196.01,7252.37,High,2025,July,5
1,FB000002,Tops,Uniqlo,Winter,L,Pink,119.64,0.0,119.64,2025-08-06,2,2.5,False,None,119.64,239.28,Low,2025,August,6
2,FB000003,Accessories,Uniqlo,Winter,None,Black,33.80,0.0,33.80,2025-08-06,22,4.3,False,None,33.80,743.60,Low,2025,August,6
3,FB000004,Shoes,Uniqlo,Spring,XL,Black,75.36,0.0,75.36,2025-07-07,48,2.6,False,None,75.36,3617.28,Medium,2025,July,7
4,FB000005,Tops,Banana Republic,Winter,XL,Black,105.02,0.0,105.02,2025-08-06,10,NaN,False,None,105.02,1050.20,Medium,2025,August,6

In [129]:
# Extract lenth of text 

data['Brand Length of text']=data['brand'].fillna('').str.len()

In [130]:
# Word count

data['Word Count']=data['brand'].fillna('').str.split().str.len()

In [131]:
data[['Brand Length of text','Word Count']]

      Brand Length of text  Word Count
0                        4           1
1                        6           1
2                        6           1
3                        6           1
4                       15           2
...                    ...         ...
2171                     5           1
2172                    15           2
2173                    15           2
2174                    10           2
2175                    10           2

[2176 rows x 2 columns]

## PART 2 - Feature Encoding

### Task 3: One-Hot Encoding

In [132]:
data.head()

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,...,is_returned,return_reason,Price per Unit,Total Value,Revenue Category,Purchase Year,Purchase Month,Purchase Day,Brand Length of text,Word Count
0,FB000001,Outerwear,Zara,Spring,XL,Red,196.01,0.0,196.01,2025-07-05,...,False,None,196.01,7252.37,High,2025,July,5,4,1
1,FB000002,Tops,Uniqlo,Winter,L,Pink,119.64,0.0,119.64,2025-08-06,...,False,None,119.64,239.28,Low,2025,August,6,6,1
2,FB000003,Accessories,Uniqlo,Winter,None,Black,33.80,0.0,33.80,2025-08-06,...,False,None,33.80,743.60,Low,2025,August,6,6,1
3,FB000004,Shoes,Uniqlo,Spring,XL,Black,75.36,0.0,75.36,2025-07-07,...,False,None,75.36,3617.28,Medium,2025,July,7,6,1
4,FB000005,Tops,Banana Republic,Winter,XL,Black,105.02,0.0,105.02,2025-08-06,...,False,None,105.02,1050.20,Medium,2025,August,6,15,2

In [133]:
# 1. Identity categorical columns

categorical_cols=['category','brand','season','color','return_reason','Revenue Category','Purchase Month']

In [134]:
categorical_cols

['category',
 'brand',
 'season',
 'color',
 'return_reason',
 'Revenue Category',
 'Purchase Month']

In [135]:
# Apply One hot encoding

encoded_data=pd.get_dummies(data,columns=categorical_cols,dtype=int)

In [136]:
# Display 
encoded_data

,product_id,size,original_price,markdown_percentage,current_price,purchase_date,stock_quantity,customer_rating,is_returned,Price per Unit,...,Purchase Month_December,Purchase Month_February,Purchase Month_January,Purchase Month_July,Purchase Month_June,Purchase Month_March,Purchase Month_May,Purchase Month_November,Purchase Month_October,Purchase Month_September
0,FB000001,XL,196.01,0.0,196.01,2025-07-05,37,3.0,False,196.01,...,0,0,0,1,0,0,0,0,0,0
1,FB000002,L,119.64,0.0,119.64,2025-08-06,2,2.5,False,119.64,...,0,0,0,0,0,0,0,0,0,0
2,FB000003,None,33.80,0.0,33.80,2025-08-06,22,4.3,False,33.80,...,0,0,0,0,0,0,0,0,0,0
3,FB000004,XL,75.36,0.0,75.36,2025-07-07,48,2.6,False,75.36,...,0,0,0,1,0,0,0,0,0,0
4,FB000005,XL,105.02,0.0,105.02,2025-08-06,10,NaN,False,105.02,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2171,FB002172,XL,31.41,0.0,31.41,2025-08-06,10,2.1,False,31.41,...,0,0,0,0,0,0,0,0,0,0
2172,FB002173,L,50.58,0.0,50.58,2025-08-06,1,3.1,True,50.58,...,0,0,0,0,0,0,0,0,0,0
2173,FB002174,None,79.37,54.8,35.88,2025-08-06,40,2.6,False,79.37,...,0,0,0,0,0,0,0,0,0,0
2174,FB002175,XL,105.52,0.0,105.52,2025-08-06,20,4.9,True,105.52,...,0,0,0,0,0,0,0,0,0,0
2175,FB002176,XXL,154.02,0.0,154.02,2025-08-06,23,1.3,False,154.02,...,0,0,0,0,0,0,0,0,0,0

In [137]:
# Shape
encoded_data.shape

(2176, 66)

### Task 4: Column Transformer

In [138]:
data.isnull().sum()

product_id                 0
category                   0
brand                      0
season                     0
size                     491
color                      0
original_price             0
markdown_percentage        0
current_price              0
purchase_date              0
stock_quantity             0
customer_rating          362
is_returned                0
return_reason           1856
Price per Unit             0
Total Value                0
Revenue Category           0
Purchase Year              0
Purchase Month             0
Purchase Day               0
Brand Length of text       0
Word Count                 0
dtype: int64

In [139]:
# Missing data handling

data['size']=data['size'].fillna('unknown')
data['customer_rating']=data['customer_rating'].fillna(data['customer_rating'].median())
data['return_reason']=data['return_reason'].fillna('unknown')

In [140]:
# Separate categorical columns

categorical_cols=['category','brand','season','size','color','return_reason','Purchase Month']

In [141]:
# Seaparate numerical columns

numerical_cols=['original_price','markdown_percentage','current_price','Price per Unit','Total Value','Purchase Year','Purchase Day','Brand Length of text','Word Count']

In [142]:
# Import important libraries

from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer

In [143]:
# Use ColumnTransformer

transformer=ColumnTransformer(transformers=[('tr1',OrdinalEncoder(categories=[['Medium','Low','High','Very High']]),['Revenue Category']),('tr2',OneHotEncoder(),categorical_cols)],remainder='passthrough')

In [144]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('tr1',
                                 OrdinalEncoder(categories=[['Medium', 'Low',
                                                             'High',
                                                             'Very High']]),
                                 ['Revenue Category']),
                                ('tr2', OneHotEncoder(),
                                 ['category', 'brand', 'season', 'size',
                                  'color', 'return_reason',
                                  'Purchase Month'])])

In [145]:
# Distribution data as input data
X=data.drop(columns=['is_returned'])

In [146]:
X

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,...,customer_rating,return_reason,Price per Unit,Total Value,Revenue Category,Purchase Year,Purchase Month,Purchase Day,Brand Length of text,Word Count
0,FB000001,Outerwear,Zara,Spring,XL,Red,196.01,0.0,196.01,2025-07-05,...,3.0,unknown,196.01,7252.37,High,2025,July,5,4,1
1,FB000002,Tops,Uniqlo,Winter,L,Pink,119.64,0.0,119.64,2025-08-06,...,2.5,unknown,119.64,239.28,Low,2025,August,6,6,1
2,FB000003,Accessories,Uniqlo,Winter,unknown,Black,33.80,0.0,33.80,2025-08-06,...,4.3,unknown,33.80,743.60,Low,2025,August,6,6,1
3,FB000004,Shoes,Uniqlo,Spring,XL,Black,75.36,0.0,75.36,2025-07-07,...,2.6,unknown,75.36,3617.28,Medium,2025,July,7,6,1
4,FB000005,Tops,Banana Republic,Winter,XL,Black,105.02,0.0,105.02,2025-08-06,...,3.0,unknown,105.02,1050.20,Medium,2025,August,6,15,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2171,FB002172,Tops,Mango,Summer,XL,Black,31.41,0.0,31.41,2025-08-06,...,2.1,unknown,31.41,314.10,Low,2025,August,6,5,1
2172,FB002173,Dresses,Banana Republic,Winter,L,Brown,50.58,0.0,50.58,2025-08-06,...,3.1,Changed Mind,50.58,50.58,Low,2025,August,6,15,2
2173,FB002174,Accessories,Banana Republic,Winter,unknown,Beige,79.37,54.8,35.88,2025-08-06,...,2.6,unknown,79.37,3174.80,Medium,2025,August,6,15,2
2174,FB002175,Bottoms,Ann Taylor,Summer,XL,Pink,105.52,0.0,105.52,2025-08-06,...,4.9,Size Issue,105.52,2110.40,Medium,2025,August,6,10,2
2175,FB002176,Shoes,Ann Taylor,Summer,XXL,White,154.02,0.0,154.02,2025-08-06,...,1.3,unknown,154.02,3542.46,Medium,2025,August,6,10,2

In [147]:
# Distribution of output data

Y=data['is_returned']

In [148]:
Y

0       False
1       False
2       False
3       False
4       False
        ...
2171    False
2172     True
2173    False
2174     True
2175    False
Name: is_returned, Length: 2176, dtype: bool

In [149]:
# Fit and Transform the dataset

In [150]:
X_transformed=transformer.fit_transform(X)

In [151]:
X_transformed

array([[2.0, 0.0, 0.0, ..., 5, 4, 1],
       [1.0, 0.0, 0.0, ..., 6, 6, 1],
       [1.0, 1.0, 0.0, ..., 6, 6, 1],
       ...,
       [0.0, 1.0, 0.0, ..., 6, 15, 2],
       [0.0, 0.0, 1.0, ..., 6, 10, 2],
       [0.0, 0.0, 0.0, ..., 6, 10, 2]], shape=(2176, 69), dtype=object)

In [152]:
le=LabelEncoder()

In [153]:
Y_label=le.fit_transform(Y)

In [154]:
Y_label

array([0, 0, 0, ..., 0, 1, 0], shape=(2176,))

## PART 3 - Feature Scaling

### Task 5: Standardization (StandardScaler)

In [155]:
data.head()

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,...,is_returned,return_reason,Price per Unit,Total Value,Revenue Category,Purchase Year,Purchase Month,Purchase Day,Brand Length of text,Word Count
0,FB000001,Outerwear,Zara,Spring,XL,Red,196.01,0.0,196.01,2025-07-05,...,False,unknown,196.01,7252.37,High,2025,July,5,4,1
1,FB000002,Tops,Uniqlo,Winter,L,Pink,119.64,0.0,119.64,2025-08-06,...,False,unknown,119.64,239.28,Low,2025,August,6,6,1
2,FB000003,Accessories,Uniqlo,Winter,unknown,Black,33.80,0.0,33.80,2025-08-06,...,False,unknown,33.80,743.60,Low,2025,August,6,6,1
3,FB000004,Shoes,Uniqlo,Spring,XL,Black,75.36,0.0,75.36,2025-07-07,...,False,unknown,75.36,3617.28,Medium,2025,July,7,6,1
4,FB000005,Tops,Banana Republic,Winter,XL,Black,105.02,0.0,105.02,2025-08-06,...,False,unknown,105.02,1050.20,Medium,2025,August,6,15,2

In [156]:
# Select numerical columns

numerical_cols=data[['original_price','markdown_percentage','current_price','Price per Unit','Total Value','Purchase Year','Purchase Day','Brand Length of text','Word Count']]

In [157]:
from sklearn.preprocessing import StandardScaler

In [158]:
ss=StandardScaler()

In [159]:
# 1. Apply StandardScaler on numerical columns

standard_value=ss.fit_transform(numerical_cols)

In [160]:
standard_value

array([[ 1.91397082, -0.65955303,  2.20668435, ..., -0.56497692,
        -0.71969508, -0.57593519],
       [ 0.4346625 , -0.65955303,  0.68171949, ..., -0.40155943,
        -0.21484128, -0.57593519],
       [-1.22808236, -0.65955303, -1.03234342, ..., -0.40155943,
        -0.21484128, -0.57593519],
       ...,
       [-0.34537869,  2.31651566, -0.99080974, ..., -0.40155943,
         2.05700083,  1.73630647],
       [ 0.16115415, -0.65955303,  0.39976972, ..., -0.40155943,
         0.79486632,  1.73630647],
       [ 1.10061274, -0.65955303,  1.36822324, ..., -0.40155943,
         0.79486632,  1.73630647]], shape=(2176, 9))

In [161]:
''' 2. Explain:
Standardization ---> It is a type of feature scaling is done to keep all value in a Standard Scale Range.
StandardScaler transforms numerical features so that their mean becomes approximate 0 and standard deviation becomes approximate 1
it uses the formula:
      
      z= (x-mean)/standard deviation

      the value of z called as scaled value

'''

' 2. Explain:\nStandardization ---> It is a type of feature scaling is done to keep all value in a Standard Scale Range.\nStandardScaler transforms numerical features so that their mean becomes approximate 0 and standard deviation becomes approximate 1\nit uses the formula:\n\n      z= (x-mean)/standard deviation\n\n      the value of z called as scaled value\n\n'

### Task 6: Normalization (MinMaxScaler)

In [162]:

from sklearn.preprocessing import MinMaxScaler

In [163]:
mm=MinMaxScaler()

In [164]:
# 1. Apply MinMaxScaler on numerical columns
normalize_value=mm.fit_transform(numerical_cols)

In [165]:
# 2. Show values scaled between 0 to 1
normalize_value

array([[0.77018396, 0.        , 0.77761754, ..., 0.13333333, 0.08333333,
        0.        ],
       [0.44498382, 0.        , 0.46293626, ..., 0.16666667, 0.25      ,
        0.        ],
       [0.07945835, 0.        , 0.109234  , ..., 0.16666667, 0.25      ,
        0.        ],
       ...,
       [0.27350537, 0.9148581 , 0.11780461, ..., 0.16666667, 1.        ,
        1.        ],
       [0.38485778, 0.        , 0.40475504, ..., 0.16666667, 0.58333333,
        1.        ],
       [0.59138137, 0.        , 0.60459846, ..., 0.16666667, 0.58333333,
        1.        ]], shape=(2176, 9))

In [166]:
# 3. Compare output with StandardScaler
'''
StandardScaler:
- Mean approxmate to 0 & Standard deviation is approxmate 1
- It also contains negative values
- Uses mean & standard deviation 

MinMaxScaler:
- Minimum is 0 & Maximum is 1
- It contains values between 0 to 1
- Uses Minimum & Maximum
'''

'\nStandardScaler:\n- Mean approxmate to 0 & Standard deviation is approxmate 1\n- It also contains negative values\n- Uses mean & standard deviation \n\nMinMaxScaler:\n- Minimum is 0 & Maximum is 1\n- It contains values between 0 to 1\n- Uses Minimum & Maximum\n'

## PART 4 - Building ML Pipeline

### Task 7: Create a Proprocessing Pipeline

In [167]:
data.head()

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,...,is_returned,return_reason,Price per Unit,Total Value,Revenue Category,Purchase Year,Purchase Month,Purchase Day,Brand Length of text,Word Count
0,FB000001,Outerwear,Zara,Spring,XL,Red,196.01,0.0,196.01,2025-07-05,...,False,unknown,196.01,7252.37,High,2025,July,5,4,1
1,FB000002,Tops,Uniqlo,Winter,L,Pink,119.64,0.0,119.64,2025-08-06,...,False,unknown,119.64,239.28,Low,2025,August,6,6,1
2,FB000003,Accessories,Uniqlo,Winter,unknown,Black,33.80,0.0,33.80,2025-08-06,...,False,unknown,33.80,743.60,Low,2025,August,6,6,1
3,FB000004,Shoes,Uniqlo,Spring,XL,Black,75.36,0.0,75.36,2025-07-07,...,False,unknown,75.36,3617.28,Medium,2025,July,7,6,1
4,FB000005,Tops,Banana Republic,Winter,XL,Black,105.02,0.0,105.02,2025-08-06,...,False,unknown,105.02,1050.20,Medium,2025,August,6,15,2

In [168]:
# Separate Data into multiple categories

In [207]:
Numerical_Data=['original_price','markdown_percentage','current_price','Price per Unit','Total Value','Purchase Year','Purchase Day','Brand Length of text','Word Count']

Ordinal_Data=['Revenue Category']

Nominal_Data=['category','brand','season','size','color','Purchase Month']

In [208]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.preprocessing import StandardScaler

In [209]:
Numerical_Pipeline=Pipeline(steps=[('imputer',SimpleImputer(strategy='mean')),('scaling',StandardScaler())])

In [210]:
Ordinal_Pipeline=Pipeline(steps=[('imputer',SimpleImputer(strategy='most_frequent')),('encoding',OrdinalEncoder(categories=[['Low','Medium','High','Very High']])),('scaling',StandardScaler())])

In [211]:
Nominal_Pipeline=Pipeline(steps=[('imputer',SimpleImputer(strategy='most_frequent')),('encoding',OneHotEncoder(handle_unknown='ignore'))])

In [212]:
# Combine them using ColumnTransformer

In [213]:
from sklearn.compose import ColumnTransformer

In [214]:
features=ColumnTransformer(transformers=[('Numerical Transformation',Numerical_Pipeline,Numerical_Data),('Ordinal Transformation',Ordinal_Pipeline,Ordinal_Data),('Nominal Transformation',Nominal_Pipeline,Nominal_Data)])

In [215]:
features

ColumnTransformer(transformers=[('Numerical Transformation',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['original_price', 'markdown_percentage',
                                  'current_price', 'Price per Unit',
                                  'Total Value', 'Purchase Year',
                                  'Purchase Day', 'Brand Length of text',
                                  'Word Count']),
                                ('Ordinal Transformation',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(str...quent')),
                                                 ('encoding',
                                                  OrdinalEncoder(categories=[['Low',
                                                                              'Medium',
                                                                              'High',
                                                                              'Very '
                                                                              'High']])),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['Revenue Category']),
                                ('Nominal Transformation',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['category', 'brand', 'season', 'size',
                                  'color', 'Purchase Month'])])

### Task 8: Full Scikit-learn Pipeline

In [216]:
# 1. Create a complete pipeline using scikit learn pipeline

In [218]:
# 2. From previous task import features

features

ColumnTransformer(transformers=[('Numerical Transformation',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['original_price', 'markdown_percentage',
                                  'current_price', 'Price per Unit',
                                  'Total Value', 'Purchase Year',
                                  'Purchase Day', 'Brand Length of text',
                                  'Word Count']),
                                ('Ordinal Transformation',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(str...quent')),
                                                 ('encoding',
                                                  OrdinalEncoder(categories=[['Low',
                                                                              'Medium',
                                                                              'High',
                                                                              'Very '
                                                                              'High']])),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['Revenue Category']),
                                ('Nominal Transformation',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['category', 'brand', 'season', 'size',
                                  'color', 'Purchase Month'])])

In [ ]:
# 3. Use simple model

In [220]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model=Pipeline(steps=[('features',features),('classifier',LogisticRegression())])

In [222]:
model

Pipeline(steps=[('features',
                 ColumnTransformer(transformers=[('Numerical Transformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['original_price',
                                                   'markdown_percentage',
                                                   'current_price',
                                                   'Price per Unit',
                                                   'Total Value',
                                                   'Purchase Year',
                                                   'Purchase Day',
                                                   'Brand Length of text',
                                                   'Word Count']),
                                                 ('Ordinal Transformation',
                                                  Pipeline(steps=[...
                                                                   OrdinalEncoder(categories=[['Low',
                                                                                               'Medium',
                                                                                               'High',
                                                                                               'Very '
                                                                                               'High']])),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['Revenue Category']),
                                                 ('Nominal Transformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['category', 'brand',
                                                   'season', 'size', 'color',
                                                   'Purchase Month'])])),
                ('classifier', LogisticRegression())])

In [224]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [225]:
X=data.drop(columns=['is_returned'])
Y=data['is_returned']

In [237]:
Y=le.fit_transform(Y)

In [ ]:
# 4. Split data into train test split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [239]:
# 5. Fit the pipeline on training data
model.fit(X_train,Y_train)

Pipeline(steps=[('features',
                 ColumnTransformer(transformers=[('Numerical Transformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['original_price',
                                                   'markdown_percentage',
                                                   'current_price',
                                                   'Price per Unit',
                                                   'Total Value',
                                                   'Purchase Year',
                                                   'Purchase Day',
                                                   'Brand Length of text',
                                                   'Word Count']),
                                                 ('Ordinal Transformation',
                                                  Pipeline(steps=[...
                                                                   OrdinalEncoder(categories=[['Low',
                                                                                               'Medium',
                                                                                               'High',
                                                                                               'Very '
                                                                                               'High']])),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['Revenue Category']),
                                                 ('Nominal Transformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['category', 'brand',
                                                   'season', 'size', 'color',
                                                   'Purchase Month'])])),
                ('classifier', LogisticRegression())])

In [ ]:
# 6. Make prediction on test data

Y_predict=model.predict(X_test)

In [241]:
from sklearn.metrics import accuracy_score

In [242]:
accuracy_score(Y_test,Y_predict)

0.8600917431192661

### Task 9: Pipeline Benefits

#### 1. Why pipelines are important in ML?
#### Pipelines combine preprocessing and model training into a single workflow . They make ML processes organized , consistent, and easier to reproduce.

#### 2. What problems do pipelines solve?
#### Pipelines help solve: -> Repeated preprocessing steps
####                       -> Data Leakage
####                       -> Inconsistent transformations between training and testing data
####                       -> Manual errors
####                       -> Difficult to maintain ML workflows

#### 3. Difference between manual preprocessing vs pipeline based preprocessing?
#### Manual Preprocessing:
#### -> Steps are preformed separately
#### -> More chances of errors
#### -> Data leakage can happen easily
#### -> Difficult to reproduce
#### -> More code and maintenance

#### Pipeline Based Preprocessing
#### -> Steps are combined into one workflow
#### -> Fewer manual errors
#### -> helps prevent data leakage
#### -> easy to preproduce
#### -> Cleaner and easier to maintain