## Task 5: Important DataFrame Functions

In [1]:
import pandas as pd

In [3]:
# Create dataframe

students={
    'Name':['Amit','Neha','Rahul','Sneha','Pooja'],
    'Marks':[78, 85, 90, 66, 72],
    'Subject':['Math','Math','Science','Science','Math']
}

students=pd.DataFrame(students)

In [4]:
students

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [5]:
# 1. Use and Print the output

students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Marks    5 non-null      int64
 2   Subject  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [6]:
students.describe()

           Marks
count   5.000000
mean   78.200000
std     9.654015
min    66.000000
25%    72.000000
50%    78.000000
75%    85.000000
max    90.000000

In [7]:
students.head()

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [8]:
students.tail()

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [20]:
# 2. Sort students by Marks in descending order

students.sort_values(by='Marks',ascending=False)

    Name  Marks  Subject
2  Rahul     90  Science
1   Neha     85     Math
0   Amit     78     Math
4  Pooja     72     Math
3  Sneha     66  Science

In [25]:
# 3. Reset index after sorting

students.reset_index(drop=True)

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math