## Task 4: Create a DataFrame

In [1]:
import pandas as pd

In [6]:
# Create dictionary dataset

students={
    'Name':['Amit','Neha','Rahul','Sneha','Pooja'],
    'Marks':[78, 85, 90, 66, 72],
    'Subject':['Math','Math','Science','Science','Math']
}

In [8]:
# 1. Convert into a dataframe

students = pd.DataFrame(students)

In [9]:
students

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [11]:
# 2. Print first 3 rows

students.head(3)

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science

In [12]:
# 3. Print last 2 rows


students.tail(2)

    Name  Marks  Subject
3  Sneha     66  Science
4  Pooja     72     Math

In [14]:
# Print DataFrame shape and columns names

students.shape

(5, 3)

In [17]:
students.columns

Index(['Name', 'Marks', 'Subject'], dtype='object')